image:
  registry: docker.io
  repository: kubetm/database-service
  tag: latest
# docker build -t kubetm/database-service:latest

tomcatAllowRemoteManagement: 1

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: "30083"  # dev(30081), qa(30082), prod(30083)

extraEnvVars:
  - name: JAVA_OPTS
    value: '-Dspring.profiles.active=prod'